# Generated by Django 4.2.1 on 2023-06-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teachers', '0002_alter_school_address_alter_school_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='school_teachers.teacher'),
        ),
    ]
