# Generated by Django 4.2.1 on 2023-06-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teachers', '0003_school_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='pros',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='quirks',
        ),
        migrations.AddField(
            model_name='teacher',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='overall_rating',
            field=models.FloatField(blank=True, default=5.0),
        ),
    ]
