# Generated by Django 4.2.1 on 2023-06-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teachers', '0004_remove_teacher_cons_remove_teacher_pros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teaching',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
