# Generated by Django 4.2.1 on 2023-06-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teachers', '0005_teacher_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='comments',
            field=models.JSONField(blank=True),
        ),
    ]
