# Generated by Django 4.2.1 on 2023-06-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teachers', '0006_alter_teacher_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
