# Generated by Django 4.2.1 on 2023-06-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_teachers', '0007_alter_teacher_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='teacher',
            name='grades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
